# Generated by Django 4.2 on 2023-04-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="marks", name="credit", field=models.FloatField(default=3),
        ),
        migrations.AddField(
            model_name="marks", name="grade", field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="marks",
            name="name",
            field=models.CharField(default="newsub", max_length=20),
        ),
    ]
