# Generated by Django 4.2 on 2023-04-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_marks_credit_marks_grade_marks_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="marks",
            name="factor",
            field=models.CharField(default="mekashreeram", max_length=30),
        ),
    ]
