# Generated by Django 4.2 on 2023-05-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_marks_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.CharField(max_length=30)),
                ('targetgpa', models.FloatField()),
                ('nosc', models.FloatField()),
            ],
        ),
    ]
