# Generated by Django 4.2 on 2023-05-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_profile_nosc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='factor',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
