# Generated by Django 4.2 on 2023-05-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_firstsem_profile_sem1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Sem1',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Sem2',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Sem3',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Sem4',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Sem5',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Sem6',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Sem7',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Sem8',
            field=models.FloatField(default=None),
        ),
    ]
